# Generated by Django 3.1.7 on 2021-03-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('docCount', models.IntegerField()),
                ('Role', models.CharField(max_length=15)),
            ],
        ),
    ]
